project_id = "yplbixiwtxhaeohombcf"

[functions.send-sms]
verify_jwt = true

[functions.facebook-leads-webhook]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.send-template-sms]
verify_jwt = true

[functions.appointment-reminders]
verify_jwt = false

[functions.transliterate-name]
verify_jwt = false
