// @ts-nocheck - Deno edge function
/**
 * Publish a Soctiv landing page to Netlify.
 *
 * Input:  { landing_page_id: string, dry_run?: boolean }
 * Output: { published_url?, published_at?, dry_run_html?, netlify_deploy_id? }
 *
 * Pipeline:
 *   1. Fetch the landing_pages row + Soctiv config from the DB.
 *   2. Stamp webhook.clientCode / webhook.productCode / webhook.url if missing.
 *   3. Resolve the per-page palette into CSS variables.
 *   4. Render the three HTML files (index, thank-you, privacy) with the
 *      mini-templating engine and the Soctiv HTML templates in this dir.
 *   5. Read the shared styles.css, client_runtime.js, pixel.js, sha256.js.
 *   6. Build a per-page runtime config JSON (window.__SOCTIV_CONFIG__) and
 *      inject it into index.html + thank-you.html.
 *   7. If dry_run: return the rendered index.html as a string (no upload).
 *   8. Else: upload the files to a PUBLIC Supabase Storage bucket
 *      (`landing-pages/<pageId>/...`) and update the landing_pages row with
 *      published_at + published_url + status. The `subdomain-router` Netlify
 *      edge function serves these files on the fly for `<sub>.soctiv.ly`.
 *
 * Why Storage and not a Netlify zip deploy: the CRM app and the landing
 * pages share the same Netlify site (soctiv.ly). Every Netlify deploy is a
 * full snapshot, so an API zip deploy of just the landing pages wiped the
 * app — and the next `git push` (app build) wiped the landing pages. Serving
 * from Storage removes that collision entirely: publishing never touches the
 * Netlify deploy, and the app build never touches the landing pages.
 *
 * Env vars used (all auto-set by Supabase — NO Netlify token needed):
 *   - SUPABASE_URL              — project URL (for the storage client + URLs)
 *   - SUPABASE_SERVICE_ROLE_KEY — to create the bucket + upload files
 *   - LANDING_BASE_DOMAIN       — (optional) public apex, default `soctiv.ly`
 */
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { renderTemplate, type TemplateContext } from './templating.ts';
// `bundled-assets.ts` is auto-generated by scripts/build-bundled-assets.cjs.
// It inlines the HTML templates, CSS, runtime JS, pixel/sha256 assets, and
// _headers file as string exports so the esbuild bundler (which Supabase
// CLI uses) picks them up. See the build script for the full rationale.
import {
    indexTpl, thankYouTpl, privacyTpl, css, runtime,
    pixelJs, sha256Js,
} from './bundled-assets.ts';

// ─── Palette resolver ──────────────────────────────────────────────────────

/**
 * The 10 curated Soctiv palettes — must match `SOCTIV_PALETTES` in
 * `src/types/soctivLandingConfig.ts`. Kept inline here so the edge function
 * has zero build-step dependency on the frontend package. Each preset is
 * a complete 28-token color system (surface, primary, secondary, tertiary,
 * trust, states, on-color text) so every section of the page renders
 * with proper color chemistry. The 4 dark palettes use warm secondaries
 * (saffron, gold, amber) so they harmonize with warm product photos.
 */
const SOCTIV_PALETTES: Record<string, Record<string, string>> = {
    'cream-sage': {
        '--bg': '#f6f3ec', '--surface': '#ffffff', '--surface-2': '#efeae0',
        '--surface-3': '#f9f6ef', '--ink': '#1f1f1c', '--ink-2': '#3a3a35',
        '--muted': '#5a584f', '--line': '#e9e4d8', '--line-2': '#ddd6c5',
        '--accent': '#9a7e57', '--accent-soft': '#ece2cd', '--accent-deep': '#6b553a',
        '--secondary': '#6e8a7c', '--secondary-soft': '#e3ebe5', '--secondary-deep': '#3f564a',
        '--tertiary': '#c08a4a', '--tertiary-soft': '#f0dfc0',
        '--sage': '#6e8a7c', '--sage-soft': '#e3ebe5', '--sage-deep': '#3f564a',
        '--success': '#4f7a64', '--success-bright': '#5e8c75', '--danger': '#a35a4a',
        '--highlight': '#f5e8d0',
        // CTA on bronze accent (mid-warm, L≈0.21) needs near-black text for
        // WCAG AA. Earlier `#3d2a10` and cream `#fbf8f0` both fell below 4.5.
        '--on-primary': '#0a0500', '--on-cta': '#0a0500',
        '--on-secondary': '#2a3a30', '--on-highlight': '#3d2a10',
    },
    'ivory-teal': {
        '--bg': '#fafaf7', '--surface': '#ffffff', '--surface-2': '#f1efe8',
        '--surface-3': '#f5f3ec', '--ink': '#0f1f1f', '--ink-2': '#2a3a3a',
        '--muted': '#4a5252', '--line': '#e3e6e0', '--line-2': '#d0d5cd',
        '--accent': '#3f7a7b', '--accent-soft': '#d8e7e6', '--accent-deep': '#1f4f50',
        '--secondary': '#5a8a7a', '--secondary-soft': '#dceae6', '--secondary-deep': '#2a5a4a',
        '--tertiary': '#d8a04a', '--tertiary-soft': '#f5e6c8',
        '--sage': '#3f7a7b', '--sage-soft': '#d8e7e6', '--sage-deep': '#1f4f50',
        '--success': '#2f6a5a', '--success-bright': '#3f8a72', '--danger': '#a35a4a',
        '--highlight': '#e8e6d8',
        '--on-primary': '#f5f8f6', '--on-cta': '#fbf8f0',
        '--on-secondary': '#1a3a30', '--on-highlight': '#1a2020',
    },
    'sand-amber': {
        '--bg': '#f5efe6', '--surface': '#ffffff', '--surface-2': '#ebe4d6',
        '--surface-3': '#efe9da', '--ink': '#2a1f12', '--ink-2': '#4a3a25',
        '--muted': '#5a4a35', '--line': '#e0d6c0', '--line-2': '#cdc1a5',
        '--accent': '#c08a4a', '--accent-soft': '#f0dfc0', '--accent-deep': '#8a5a2a',
        '--secondary': '#7a8a4a', '--secondary-soft': '#e8e0c5', '--secondary-deep': '#4a5a25',
        '--tertiary': '#a85a3a', '--tertiary-soft': '#f0d4c0',
        '--sage': '#8a7a4a', '--sage-soft': '#e8e0c5', '--sage-deep': '#5a4a25',
        '--success': '#7a8a4a', '--success-bright': '#9aaa5a', '--danger': '#a35a3a',
        '--highlight': '#f5e2c5',
        // CTA on amber accent (mid-warm gold, L≈0.32) needs dark text — cream
        // `#fbf8f0` was at 2.84:1 (FAIL). Switched to warm near-black.
        '--on-primary': '#3a2010', '--on-cta': '#1a1008',
        '--on-secondary': '#2a3010', '--on-highlight': '#3a2010',
    },
    'charcoal-mint': {
        // Dark luxe — RE-TINTED with warm saffron secondary so the page
        // harmonizes with warm product photos. Mint is now a micro-accent only.
        '--bg': '#0f1417', '--surface': '#161c20', '--surface-2': '#1c2429',
        '--surface-3': '#222b30', '--ink': '#f0f3f5', '--ink-2': '#c0c8cc',
        '--muted': '#a0aab0', '--line': '#2a3338', '--line-2': '#36403f',
        '--accent': '#7ce0c2', '--accent-soft': '#1c3a35', '--accent-deep': '#3fa890',
        '--secondary': '#e8b85a', '--secondary-soft': '#3a3020', '--secondary-deep': '#a87a2a',
        '--tertiary': '#5ae0c8', '--tertiary-soft': '#1a3a32',
        '--sage': '#7ce0c2', '--sage-soft': '#1c3a35', '--sage-deep': '#a8f0d8',
        '--success': '#7ce0c2', '--success-bright': '#a8f0d8', '--danger': '#ff7a6a',
        '--highlight': '#2a2a30',
        '--on-primary': '#0a2a22', '--on-cta': '#1a1208',
        '--on-secondary': '#f5e8c8', '--on-highlight': '#e8b85a',
    },
    'navy-coral': {
        // Dark luxe — RE-TINTED with warm gold secondary (was cool blue).
        '--bg': '#0d1825', '--surface': '#142133', '--surface-2': '#1a2a3f',
        '--surface-3': '#22344c', '--ink': '#f5f7fa', '--ink-2': '#c5cfd9',
        '--muted': '#a0b0c0', '--line': '#2a3a52', '--line-2': '#36456a',
        '--accent': '#ff6a5a', '--accent-soft': '#3a1f1c', '--accent-deep': '#c44030',
        '--secondary': '#e8b85a', '--secondary-soft': '#3a3020', '--secondary-deep': '#a87a2a',
        '--tertiary': '#7aa8ff', '--tertiary-soft': '#1a2a4a',
        '--sage': '#5a8aff', '--sage-soft': '#1c2a4a', '--sage-deep': '#a8bfff',
        '--success': '#5ae0a8', '--success-bright': '#7ce8c0', '--danger': '#ff6a5a',
        '--highlight': '#2a2a3a',
        '--on-primary': '#3a0a08', '--on-cta': '#1a0808',
        '--on-secondary': '#f5e8c8', '--on-highlight': '#e8b85a',
    },
    'blush-bronze': {
        '--bg': '#faf3ee', '--surface': '#ffffff', '--surface-2': '#f5e8de',
        '--surface-3': '#f9ede2', '--ink': '#2a1a14', '--ink-2': '#4a3530',
        '--muted': '#5a4030', '--line': '#ead9c8', '--line-2': '#d9c0a8',
        '--accent': '#b8723a', '--accent-soft': '#f0dcc4', '--accent-deep': '#7a4a20',
        '--secondary': '#a86a5a', '--secondary-soft': '#f0d8d0', '--secondary-deep': '#6a3a2a',
        '--tertiary': '#d8a85a', '--tertiary-soft': '#f5e8c8',
        '--sage': '#a86a5a', '--sage-soft': '#f0d8d0', '--sage-deep': '#7a4a3a',
        '--success': '#7a9a6a', '--success-bright': '#9ab07a', '--danger': '#a85a4a',
        '--highlight': '#f5e0d0',
        // CTA on bronze accent (mid-warm, L≈0.21) needs near-black text —
        // cream `#fbf8f0` was at 3.59:1 (BAD) and `#3a1a08` was at 4.14:1
        // (AA-large only). Switched both to warm near-black `#0a0500`.
        '--on-primary': '#0a0500', '--on-cta': '#0a0500',
        '--on-secondary': '#2a1008', '--on-highlight': '#3a1a08',
    },
    'slate-violet': {
        '--bg': '#f4f4f8', '--surface': '#ffffff', '--surface-2': '#e8e8f0',
        '--surface-3': '#eeeef4', '--ink': '#1a1a2a', '--ink-2': '#3a3a4a',
        '--muted': '#6a6a7a', '--line': '#d8d8e0', '--line-2': '#c5c5d0',
        '--accent': '#6a4ae8', '--accent-soft': '#e0d8f5', '--accent-deep': '#3a1aa0',
        '--secondary': '#4a6ae8', '--secondary-soft': '#d8e0f5', '--secondary-deep': '#1a3aa0',
        '--tertiary': '#4ae8c8', '--tertiary-soft': '#d8f5ec',
        '--sage': '#4a6ae8', '--sage-soft': '#d8e0f5', '--sage-deep': '#2a3aa0',
        '--success': '#4a8a6a', '--success-bright': '#6aaa8a', '--danger': '#a84a4a',
        '--highlight': '#e8e6f0',
        '--on-primary': '#f5f0fa', '--on-cta': '#fbf8f0',
        '--on-secondary': '#0a1a4a', '--on-highlight': '#1a1a3a',
    },
    'espresso-emerald': {
        // Dark warm — RE-TINTED with warm amber secondary (was mint).
        '--bg': '#1a120c', '--surface': '#221812', '--surface-2': '#2a1f18',
        '--surface-3': '#322520', '--ink': '#f5ebe0', '--ink-2': '#c5b5a0',
        '--muted': '#a89880', '--line': '#3a2a1f', '--line-2': '#4a3a2a',
        '--accent': '#5ae0a0', '--accent-soft': '#1c3a2a', '--accent-deep': '#3aa070',
        '--secondary': '#e8a85a', '--secondary-soft': '#3a2a1a', '--secondary-deep': '#a8702a',
        '--tertiary': '#a8e0c8', '--tertiary-soft': '#1c3a2a',
        '--sage': '#5ae0a0', '--sage-soft': '#1c3a2a', '--sage-deep': '#a8f0c5',
        '--success': '#5ae0a0', '--success-bright': '#a8f0c5', '--danger': '#ff7a5a',
        '--highlight': '#2a201a',
        '--on-primary': '#0a2010', '--on-cta': '#1a1008',
        '--on-secondary': '#f5e8c8', '--on-highlight': '#e8a85a',
    },
    'cloud-lavender': {
        '--bg': '#faf8fc', '--surface': '#ffffff', '--surface-2': '#f0eaf5',
        '--surface-3': '#f5f0fa', '--ink': '#1f1a2a', '--ink-2': '#3a3540',
        '--muted': '#524858', '--line': '#e5dceb', '--line-2': '#d0c5d8',
        '--accent': '#9a7ad8', '--accent-soft': '#ebdff5', '--accent-deep': '#5a3aa0',
        '--secondary': '#d8a8c0', '--secondary-soft': '#f5e0ea', '--secondary-deep': '#8a5a7a',
        '--tertiary': '#7a9ad8', '--tertiary-soft': '#dfe5f5',
        '--sage': '#7a9ad8', '--sage-soft': '#dfe5f5', '--sage-deep': '#5a4a8a',
        '--success': '#6a9a7a', '--success-bright': '#8aaa8a', '--danger': '#a85a7a',
        '--highlight': '#f0e8f5',
        // CTA on lavender accent (mid purple, L≈0.30) needs dark text — cream
        // `#fbf8f0` was at 3.22:1 (BAD). Switched to dark indigo `#1a1230`.
        '--on-primary': '#2a1a4a', '--on-cta': '#1a1230',
        '--on-secondary': '#3a1a2a', '--on-highlight': '#2a1a3a',
    },
    'ink-rose': {
        // Dark romantic — RE-TINTED with warm gold secondary (was near-accent rose).
        '--bg': '#0f0d12', '--surface': '#171420', '--surface-2': '#1f1a2a',
        '--surface-3': '#272234', '--ink': '#f5f0f5', '--ink-2': '#c5bcc5',
        '--muted': '#a0929a', '--line': '#2a2530', '--line-2': '#3a3540',
        '--accent': '#f0a8b8', '--accent-soft': '#3a2a30', '--accent-deep': '#a86878',
        '--secondary': '#e8c878', '--secondary-soft': '#3a3020', '--secondary-deep': '#a8883a',
        '--tertiary': '#a8c8f0', '--tertiary-soft': '#1a2a3a',
        '--sage': '#e0a8b8', '--sage-soft': '#3a2a30', '--sage-deep': '#f5c5d0',
        '--success': '#a8e0b8', '--success-bright': '#c5f0d0', '--danger': '#ff7a8a',
        '--highlight': '#2a2530',
        '--on-primary': '#3a1a22', '--on-cta': '#1a1008',
        '--on-secondary': '#f5e8c8', '--on-highlight': '#e8c878',
    },
};

const DEFAULT_PALETTE = 'cream-sage';

/** Public apex the landing pages live under. Subdomain pages are served at
 *  `https://<sub>.<LANDING_BASE_DOMAIN>/` and the no-subdomain fallback at
 *  `https://<LANDING_BASE_DOMAIN>/p/<pageId>/`. Overridable via env so the
 *  same function works if the brand domain ever changes. */
const LANDING_BASE_DOMAIN = (Deno.env.get('LANDING_BASE_DOMAIN') || 'soctiv.ly')
    .trim()
    .toLowerCase()
    .replace(/^https?:\/\//, '')
    .replace(/\/+$/, '');

/** CSS `font-family` value per user-selected font. The first family is
 *  always the user's pick; the rest are a deliberate fallback chain so
 *  the page is readable even before Google Fonts loads. The same stack
 *  is emitted into the `--font` custom property by `paletteToCssVars`. */
const FONT_STACK: Record<string, string> = {
    // Alexandria uses the EXACT same stack as the home page
    // (`src/index.css:463` body rule). Keeping these two stacks identical
    // prevents the published preview from rendering with visibly
    // different Latin/numeric glyphs or kerning than the home page.
    // Other Arabic-first fonts keep the dedicated Arabic fallback chain
    // because their primary family is Arabic-specific and would otherwise
    // drop straight to a Latin system font for digits and Latin words.
    'Alexandria':
        'Alexandria, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    'IBM Plex Sans Arabic':
        '"IBM Plex Sans Arabic", "IBM Plex Sans", "Segoe UI Arabic", system-ui, -apple-system, Roboto, sans-serif',
    'Cairo':
        '"Cairo", "Segoe UI Arabic", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    'Tajawal':
        '"Tajawal", "Segoe UI Arabic", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    'Noto Sans Arabic':
        '"Noto Sans Arabic", "Noto Sans", "Segoe UI Arabic", system-ui, -apple-system, Roboto, sans-serif',
    'Readex Pro':
        '"Readex Pro", "Segoe UI Arabic", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    'Almarai':
        '"Almarai", "Segoe UI Arabic", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    'Inter':
        '"Inter", "Segoe UI Arabic", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
};

/** Google Fonts URL-safe family name (no quoting, plus for space). */
const FONT_MAP: Record<string, string> = {
    'Alexandria': 'Alexandria',
    'IBM Plex Sans Arabic': 'IBM+Plex+Sans+Arabic',
    'Cairo': 'Cairo',
    'Tajawal': 'Tajawal',
    'Noto Sans Arabic': 'Noto+Sans+Arabic',
    'Readex Pro': 'Readex+Pro',
    'Almarai': 'Almarai',
    'Inter': 'Inter',
};

/** Resolve a Soctiv config theme into CSS custom-property declarations
 *  wrapped in `:root { ... }`. Emits both the palette tokens AND a
 *  `--font` declaration so the rendered HTML always carries the user's
 *  font choice in the first slot of the stack. Without `--font` in this
 *  block, the body fell back to whichever family was hardcoded first in
 *  `styles.css` (the old "Alexandria never renders" bug). */
function paletteToCssVars(theme: any): string {
    const paletteKey = theme?.palette && SOCTIV_PALETTES[theme.palette]
        ? theme.palette
        : DEFAULT_PALETTE;
    const vars = SOCTIV_PALETTES[paletteKey];
    const body = Object.entries(vars)
        .map(([k, v]) => `${k}: ${v}`)
        .join('; ');
    return `:root { ${body}; --font: ${fontStack(theme)}; }`;
}

/** Resolve the Google Fonts URL-safe font name for the `theme.font` value. */
function fontName(theme: any): string {
    return FONT_MAP[theme?.font] || 'Alexandria';
}

function fontStack(theme: any): string {
    return FONT_STACK[theme?.font] || FONT_STACK['Alexandria'];
}

// ─── Tracking config script builder ─────────────────────────────────────────

/**
 * Build the inlined `<script>window.SOCTIV_TRACK_CONFIG = {...};</script>`
 * block that template_index.html injects before sha256.js + pixel.js.
 *
 * Why this lives here and not in the template: the raw value contains
 * user-controlled strings (capiUrl, testEventCode, product name) that
 * would otherwise be substituted via `{{{...}}}` in the template — but
 * `{{{...}}}` is a raw, un-escaped substitution, so a malicious or
 * paste-of-`</script>` value would break out of the inlined script tag
 * and run arbitrary code in the published page (an XSS sink affecting
 * every page with the user's domain).
 *
 * The safe pattern is:
 *   1. JSON.stringify encodes every user value as a JS literal — quotes,
 *      backslashes, and control chars are escaped automatically.
 *   2. The only sequence the HTML parser's raw-text script state treats
 *      as a terminator is `</script>` (case-insensitive). We escape that
 *      specifically — both the original and the JS-escaped form `<\/script>`
 *      that the parser would otherwise pass through as data but the runtime
 *      would re-emit on a future JSON.stringify round-trip.
 *
 * Returns the literal script block, ready to drop into the rendered HTML.
 * Always returns a valid script even if tracking is disabled — but the
 * caller is responsible for gating this behind `{{#if tracking.pixelId}}`
 * so a no-op script isn't emitted.
 */
function buildTrackConfigScript(tracking: any, product: any, pageToken: string = '', pageId: string = ''): string {
    const safeConfig = {
        pixelId: String(tracking?.pixelId || ''),
        capiUrl: String(tracking?.capiUrl || ''),
        testEventCode: String(tracking?.testEventCode || ''),
        debug: !!tracking?.debug,
        // Per-page HMAC token — closes the conversion-fraud vector where
        // anyone with the capiUrl can POST fake Lead/Purchase events. The
        // capi-proxy recomputes HMAC(CAPI_SHARED_SECRET, page_id) and
        // verifies it matches this value. Empty when CAPI_SHARED_SECRET
        // is unset on the publish function (dev only — proxy skips check).
        pageToken: String(pageToken || ''),
        pageId: String(pageId || ''),
        product: {
            id: String(product?.id || product?.code || ''),
            name: String(product?.nameArabic || product?.name || ''),
            category: String(product?.category || ''),
            currency: String(product?.currency || ''),
            value: Number(product?.value || product?.unitPrice || 0) || 0,
        },
    };
    // The two `</script>` patterns we need to defend against:
    //   1. Literal `</script>` inside a user string (most common — e.g. a
    //      product name or test event code containing that exact sequence).
    //   2. The JSON-escaped form `<\/script>` that JSON.stringify would
    //      otherwise emit as-is — the HTML parser's raw-text scan would
    //      leave it untouched, but a future consumer that round-trips the
    //      value through JSON.parse + re-stringify would emit the dangerous
    //      `</script>` form, so escape it now to be future-proof.
    const json = JSON.stringify(safeConfig)
        .replace(/<\/(script)/gi, '<\\/$1')
        .replace(/<\/(script)[\s]/gi, '<\\/$1');
    // The `<\/script>` in the closing tag is a JS string literal escape —
    // it's the same defense pattern as the runtime config below
    // (see `</script>` -> `<\/script>` in `configJson`).
    return `<script>window.SOCTIV_TRACK_CONFIG = ${json};<\/script>`;
}

// ─── Form copy defaults (Arabic) ──────────────────────────────────────────

const FORM_COPY_DEFAULTS = {
    submitText: 'تأكيد الطلب',
    nameField: 'الاسم الكامل',
    phoneField: 'رقم الهاتف',
    locationField: 'المدينة والعنوان',
    namePlaceholder: 'مثال: أحمد محمد',
    locationPlaceholder: 'مثال: شارع الجمهورية، طرابلس',
    phoneError: 'يرجى إدخال رقم هاتف ليبي صالح (10 أرقام يبدأ بـ 09).',
    nameError: 'يرجى إدخال الاسم الكامل.',
    locationError: 'يرجى إدخال المدينة والعنوان.',
    submittingText: 'جاري الإرسال…',
};

const PRICING_COPY_DEFAULTS = {
    stepperLabel: 'كم قطعة تريد؟',
    stepperAria: 'اختر الكمية',
    minusAria: 'إنقاص الكمية',
    plusAria: 'زيادة الكمية',
    unitLabel: 'سعر القطعة الواحدة',
    subtotalLabel: 'سعر القطعة',
    deliveryLabel: 'رسوم التوصيل',
    deliveryFree: 'مجاناً',
    discountLabel: 'التخفيض',
    totalLabel: 'الإجمالي الكلي',
};

// ─── Handler ────────────────────────────────────────────────────────────────

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // ─── Parse input
    let body: { landing_page_id?: string; dry_run?: boolean };
    try {
      body = await req.json();
    } catch {
      return new Response(JSON.stringify({ error: 'Invalid JSON body' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    const landingPageId = body.landing_page_id;
    const dryRun = !!body.dry_run;
    if (!landingPageId) {
      return new Response(JSON.stringify({ error: 'Missing landing_page_id' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // ─── Fetch page + config
    // Pull both `subdomain` and `custom_domain` so we can compute the
    // external published URL (clean <brand>.soctiv.ly, not the bare Netlify
    // deploy URL with a <pageId>/ subfolder).
    const { data: page, error: pageError } = await supabase
      .from('landing_pages')
      .select('id, client_id, product_id, product_dna_id, status, config, subdomain, custom_domain')
      .eq('id', landingPageId as any)
      .single();

    if (pageError || !page) {
      return new Response(JSON.stringify({ error: 'Landing page not found' }), {
        status: 404,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    const config: any = (page as any).config;
    if (!config || typeof config !== 'object' || Object.keys(config).length === 0) {
      return new Response(JSON.stringify({ error: 'Landing page has no config. Generate it first.' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // ─── Resolve the external published URL (security/external-feel fix)
    //
    // Priority:
    //   1. custom_domain  → https://<custom_domain>            (the user's own DNS)
    //   2. subdomain      → https://<subdomain>.soctiv.ly      (our wildcard)
    //   3. fallback       → <deployUrl>/<pageId>/              (Netlify, ugly but works)
    //
    // Before this fix, `published_url` was the bare Netlify deploy URL —
    // opening "View live" in the editor landed on a Netlify site page
    // (often a 404) and the privacy link resolved to a path that included
    // the internal page id, which felt like an internal route rather
    // than an external landing page.
    //
    // NOTE: this URL is what the runtime templates see via
    // `{{publishedBaseUrl}}` (used for the privacy-policy absolute link).
    // It is ALSO what we write back to `landing_pages.published_url`,
    // so the editor's "View live" button + the published card both
    // open the right page.
    const customDomain = (page as any).custom_domain
      ? String((page as any).custom_domain).trim().toLowerCase()
      : '';
    const subdomain = (page as any).subdomain
      ? String((page as any).subdomain).trim().toLowerCase()
      : '';
    // Stash on config so the template substitution at the bottom can
    // pick it up without threading it through every helper.
    (config as any).__resolvedSubdomain = subdomain;
    (config as any).__resolvedCustomDomain = customDomain;

    // ─── Stamp webhook + tracking defaults
    if (!config.webhook) config.webhook = {};
    if (!config.webhook.url) {
      config.webhook.url = `${supabaseUrl}/functions/v1/facebook-leads-webhook`;
    }
    if (!config.webhook.thankYouUrl) config.webhook.thankYouUrl = 'thank-you.html';
    if (!config.webhook.source) config.webhook.source = 'Landing Page';
    if (!config.webhook.clientCode) {
      const { data: client } = await supabase
        .from('clients')
        .select('webhook_code')
        .eq('id', (page as any).client_id as any)
        .single();
      if (client?.webhook_code) config.webhook.clientCode = client.webhook_code;
    }
    if (!config.webhook.productCode) {
      const { data: product } = await supabase
        .from('products')
        .select('code')
        .eq('id', (page as any).product_id as any)
        .single();
      if (product?.code) config.webhook.productCode = product.code;
    }
    if (!config.tracking) config.tracking = {};
    if (!config.tracking.capiUrl) {
      config.tracking.capiUrl = `${supabaseUrl}/functions/v1/capi-proxy`;
    }
    if (typeof config.tracking.debug !== 'boolean') config.tracking.debug = false;

    // ─── Tracking field normalization
    // Defensive: a pixelId of '0' is truthy by === but treated as falsy by
    // the templating engine's `isTruthy` (0 === 0 check at templating.ts:194),
    // which means `{{#if tracking.pixelId}}` would silently skip the tracking
    // scripts and the user would have no idea why their pixel isn't firing.
    // Same risk for whitespace or non-digit characters that survived the
    // editor's `replace(/\D/g, '')` filter. Normalize here so the template
    // sees a clean string-or-empty value, and the conditional works as
    // expected.
    if (typeof config.tracking.pixelId === 'string') {
        const cleaned = config.tracking.pixelId.replace(/\D/g, '');
        // Meta pixel IDs are 10-20 digits; anything outside that is invalid
        // and we treat as "pixel disabled" (the tracking scripts are omitted).
        if (cleaned === '0' || (cleaned.length > 0 && (cleaned.length < 10 || cleaned.length > 20))) {
            config.tracking.pixelId = '';
        } else {
            config.tracking.pixelId = cleaned;
        }
    } else {
        config.tracking.pixelId = '';
    }

    // ─── Theme defaults
    if (!config.theme) config.theme = { palette: DEFAULT_PALETTE, font: 'Alexandria' };
    if (!SOCTIV_PALETTES[config.theme.palette]) config.theme.palette = DEFAULT_PALETTE;
    // Keep `config.theme.font` as the user-picked name (e.g. "IBM Plex Sans
    // Arabic", "Readex Pro"). The previous code overwrote it with the URL-safe
    // form ("IBM+Plex+Sans+Arabic") via `fontName`, but `FONT_STACK` keys are
    // the human-readable names — so `fontStack(theme)` fell back to Alexandria
    // for any font whose name contained a space. The URL-safe form is not
    // actually needed anywhere (the template hardcodes the Google Fonts <link>
    // with all 8 families), so the rewrite was just breaking the stack lookup.

    // ─── Form copy defaults
    if (!config.form) config.form = {};
    Object.assign(config.form, FORM_COPY_DEFAULTS);

    // ─── Pricing copy defaults
    if (!config.pricing) config.pricing = {};
    Object.assign(config.pricing, PRICING_COPY_DEFAULTS);

    // ─── Business defaults
    if (!config.business) {
      config.business = { brand: 'soctiv', copyright: 'جميع الحقوق محفوظة', supportEmail: '', privacyEmail: '' };
    }
    if (!config.business.brand) config.business.brand = 'soctiv';
    if (!config.business.brandInitial) {
      config.business.brandInitial = String(config.business.brand || 's').charAt(0);
    }
    // The footer template hardcodes the `© <year> <brand> —` prefix
    // (see template_index.html:339 / template_thank_you.html:169). Stamp
    // only the trailing phrase so the prefix doesn't render twice.
    if (!config.business.copyright) {
      config.business.copyright = 'جميع الحقوق محفوظة';
    }

    // ─── SEO defaults
    if (!config.seo) config.seo = {};
    if (!config.seo.year) config.seo.year = String(new Date().getFullYear());
    if (!config.seo.title && config.product?.nameArabic) {
      config.seo.title = `${config.product.nameArabic} — الدفع عند الاستلام | ${config.business.brand}`;
    }
    if (!config.seo.description && config.hero?.subline) {
      config.seo.description = String(config.hero.subline).slice(0, 160);
    }

    // ─── Trust defaults — Phase 5: migrate legacy `string[]` shape to the
    // new `{ enabled, items }` strip. Same logic as
    // src/services/soctivLandingPreview.ts `buildPreviewContext`.
    const trustStrip = (
        v: string[] | { enabled?: boolean; items: string[] } | undefined,
        fallback: string[]
    ): { enabled: boolean; items: string[] } => {
        if (Array.isArray(v)) {
            return {
                enabled: true,
                items: v.length > 0 ? v.slice(0, 6) : fallback,
            };
        }
        const obj = v || {};
        return {
            enabled: obj.enabled !== false,
            items: Array.isArray(obj.items) && obj.items.length > 0
                ? obj.items
                : fallback,
        };
    };
    if (!config.trust) {
        config.trust = {
            badges: trustStrip(undefined, ['الدفع عند الاستلام', 'توصيل مجاني', 'ضمان سنة']),
            row: trustStrip(undefined, ['دفع عند الاستلام', 'توصيل مجاني']),
        };
    } else {
        config.trust = {
            badges: trustStrip(config.trust.badges as any, ['الدفع عند الاستلام', 'توصيل مجاني', 'ضمان سنة']),
            row: trustStrip(config.trust.row as any, ['دفع عند الاستلام', 'توصيل مجاني']),
        };
    }

    // ─── Reviews defaults — Phase 5 toggle (default ON for legacy configs)
    if (!config.reviews) {
        config.reviews = { enabled: true, heading: 'ماذا يقول عملاؤنا', subheading: '', items: [] };
    } else {
        config.reviews = { ...config.reviews, enabled: config.reviews.enabled !== false };
    }

    // ─── Templates + assets
    // All inlined via `bundled-assets.ts` so the esbuild bundler ships
    // them inside the function bundle. See the comment in that file for
    // why we can't use Deno.readTextFile here.
    //
    // The two legacy variables (`pixelJs`, `sha256Js`) used to be `let`
    // with try/catch fallbacks. Now they're guaranteed to be non-empty
    // strings from the import (build script errors out if the source
    // files are missing), so we keep the same name without the fallback.
    void pixelJs;
    void sha256Js;

    // ─── Build the template context
    // `__publishedBaseUrl` is the absolute origin (no trailing slash) of
    // the live page. Templates use it to build absolute links for the
    // privacy policy + back-to-home + og:url — these used to be relative
    // hrefs, which resolved to the bare Netlify deploy URL with the
    // internal page-id subfolder visible in the address bar. Absolute
    // URLs make the published page feel like an external site (e.g.
    // https://my-brand.soctiv.ly/privacy-policy.html) and keep the
    // user inside the same origin when they click around.
    //
    // If the page has a subdomain or custom_domain, we know the final
    // URL up-front and can render with the absolute base right away.
    // If neither is set, we render with an empty placeholder, deploy,
    // and re-deploy with the real Netlify URL — see the two-pass block
    // further down.
    // We always know the final external URL up front now (Storage serving is
    // deterministic — no two-pass "deploy then learn the URL" dance):
    //   custom_domain → https://<custom_domain>
    //   subdomain     → https://<subdomain>.soctiv.ly
    //   neither       → https://soctiv.ly/p/<pageId>/   (path fallback, still
    //                   reachable via the same subdomain-router edge function)
    const knownBaseUrl = customDomain
      ? `https://${customDomain}`
      : subdomain
        ? `https://${subdomain}.${LANDING_BASE_DOMAIN}`
        : `https://${LANDING_BASE_DOMAIN}/p/${landingPageId}`;

    // ─── Per-page HMAC token (defense in depth against conversion fraud).
    // The capi-proxy requires this header to be a valid HMAC-SHA256 of the
    // page id using CAPI_SHARED_SECRET. We compute it here so the secret
    // never reaches the browser (only the per-page token does).
    const capiSecret = Deno.env.get('CAPI_SHARED_SECRET') || '';
    let pageToken = '';
    if (capiSecret) {
      try {
        const enc = new TextEncoder();
        const key = await crypto.subtle.importKey(
          'raw', enc.encode(capiSecret),
          { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
        );
        const sigBytes = await crypto.subtle.sign('HMAC', key, enc.encode(landingPageId));
        pageToken = 'sha256=' + [...new Uint8Array(sigBytes)]
          .map((b) => b.toString(16).padStart(2, '0')).join('');
      } catch (e) {
        console.warn('page token generation failed (capi-proxy will reject if it requires auth):', (e as Error).message);
      }
    }

    const ctx: TemplateContext = {
      ...config,
      __cssVars: paletteToCssVars(config.theme),
      // Pre-built inlined tracking-config script. See buildTrackConfigScript
      // for why this is server-built and not templated field-by-field.
      __trackConfigScript: buildTrackConfigScript(config.tracking, config.product, pageToken, landingPageId),
      __publishedBaseUrl: knownBaseUrl,
      // The page id flows into the runtime via the SOCTIV_CONFIG script so
      // pixel.js can include it in CAPI POSTs (the proxy verifies the
      // signature against this id).
      __pageId: landingPageId,
    };

    // ─── Render the three page templates with the inlined config script.
    // `injectBeforeRuntime` is shared between the render and any later
    // re-render (see the two-pass block below) — it splices the runtime
    // config right before <script src="runtime.js"></script> so the
    // runtime sees the config on first eval.
    const renderAll = (baseUrl: string): {
        indexHtml: string;
        thankYouHtml: string;
        privacyHtml: string;
    } => {
        const localCtx = { ...ctx, __publishedBaseUrl: baseUrl };
        const configJson = JSON.stringify({
          product: config.product,
          pricing: {
            tiers: config.pricing?.tiers || [],
            maxQty: config.pricing?.maxQty || 5,
            discountLabel: config.pricing?.discountLabel || 'التخفيض',
          },
          form: config.form,
          webhook: config.webhook,
          tracking: { debug: !!config.tracking?.debug },
        }).replace(/<\/script>/gi, '<\\/script>');
        const configScript = `<script>window.__SOCTIV_CONFIG__ = ${configJson};<\/script>\n`;
        const injectBeforeRuntime = (html: string): string => {
            // Function-callback replacement, NOT a string. The config contains
            // user-controlled strings (product name, headline, CTA text, …).
            // If any of them happens to contain `$&` (e.g. a literal `$&` in a
            // headline), `String.replace` would interpret it as "the matched
            // substring" — replacing it with `<script src="runtime.js"></script>`
            // or `</body>` (whichever matched) — and leak the literal HTML tag
            // into the page body as visible text. The function form short-circuits
            // the interpretation. Same fix as
            // src/services/soctivLandingPreview.ts `injectConfigScript`.
            if (html.includes('<script src="runtime.js"></script>')) {
                return html.replace(
                    '<script src="runtime.js"></script>',
                    () => configScript + '<script src="runtime.js"></script>'
                );
            }
            return html.replace('</body>', () => configScript + '</body>');
        };
        return {
            indexHtml: injectBeforeRuntime(renderTemplate(indexTpl, localCtx)),
            thankYouHtml: injectBeforeRuntime(renderTemplate(thankYouTpl, localCtx)),
            privacyHtml: renderTemplate(privacyTpl, localCtx),
        };
    };

    // ─── Dry run: return the rendered HTML
    if (dryRun) {
      const dry = renderAll(knownBaseUrl);
      return new Response(
        JSON.stringify({
          dry_run_html: dry.indexHtml,
          index_length: dry.indexHtml.length,
          thank_you_length: dry.thankYouHtml.length,
          privacy_length: dry.privacyHtml.length,
          published_base_url: knownBaseUrl || null,
        }),
        { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // ─── Publish target: a PUBLIC Supabase Storage bucket.
    // The rendered files are uploaded here and served on the fly by the
    // `subdomain-router` Netlify edge function. No Netlify token, no zip,
    // no deploy collision with the CRM app's git build (see the file header).
    const BUCKET = 'landing-pages';
    // Ensure the bucket exists + is public. Idempotent: only the first ever
    // publish actually creates it; afterwards createBucket returns an
    // "already exists" error we intentionally swallow.
    try {
      const { error: bucketErr } = await supabase.storage.createBucket(BUCKET, {
        public: true,
        fileSizeLimit: '5MB',
      });
      if (bucketErr && !/exist/i.test(bucketErr.message || '')) {
        console.warn('createBucket warning:', bucketErr.message);
      }
    } catch (e) {
      console.warn('createBucket threw:', (e as Error).message);
    }

    // Each page lives under its own `<pageId>/` prefix in the bucket. The
    // edge function rewrites `<sub>.soctiv.ly/<path>` → `<pageId>/<path>`,
    // so the relative asset refs in the rendered HTML (styles.css, runtime.js,
    // thank-you.html, …) resolve correctly without any per-page rewriting.
    const pageId = (page as any).id as string;

    // Render the three pages once. We already know the final external URL
    // (subdomain / custom domain / /p/<id> fallback) so there's no two-pass
    // deploy dance anymore.
    const rendered = renderAll(knownBaseUrl);

    const HTML = 'text/html; charset=utf-8';
    const CSS = 'text/css; charset=utf-8';
    const JS = 'application/javascript; charset=utf-8';
    const files: Array<{ path: string; body: string; type: string }> = [
      { path: `${pageId}/index.html`, body: rendered.indexHtml, type: HTML },
      { path: `${pageId}/thank-you.html`, body: rendered.thankYouHtml, type: HTML },
      { path: `${pageId}/privacy-policy.html`, body: rendered.privacyHtml, type: HTML },
      { path: `${pageId}/styles.css`, body: css, type: CSS },
      { path: `${pageId}/runtime.js`, body: runtime, type: JS },
    ];
    if (pixelJs) files.push({ path: `${pageId}/pixel.js`, body: pixelJs, type: JS });
    if (sha256Js) files.push({ path: `${pageId}/sha256.js`, body: sha256Js, type: JS });

    // Upload every file with upsert so re-publishing overwrites in place.
    // cacheControl is short (60s) so edits go live quickly. Any failure
    // aborts the publish — a half-uploaded page (HTML present but runtime.js
    // missing) is worse than a clear error the user can retry.
    const uploadOne = async (path: string, body: string, type: string) => {
      const { error } = await supabase.storage
        .from(BUCKET)
        .upload(path, new Blob([body], { type }), {
          contentType: type,
          upsert: true,
          cacheControl: '60',
        });
      if (error) throw new Error(`Failed to upload ${path}: ${error.message}`);
    };
    for (const f of files) {
      await uploadOne(f.path, f.body, f.type);
    }

    // ─── Rebuild the subdomain → pageId map the edge router reads.
    // The `subdomain-router` edge function fetches `_map.json` to resolve
    // `<sub>.soctiv.ly` → `<pageId>`, then serves `<pageId>/<path>` from this
    // bucket. This single file is the WHOLE routing table, so it must list
    // EVERY published page that has a subdomain — not just the one we're
    // publishing now. We add the current page explicitly because its row may
    // still say 'draft' until the update below commits.
    const { data: allPublishedPages, error: allPubError } = await supabase
      .from('landing_pages')
      .select('id, subdomain')
      .not('subdomain', 'is', null)
      .neq('subdomain', '')
      .eq('status', 'published' as any);
    if (allPubError) {
      console.warn('Failed to query published pages for the subdomain map:', allPubError.message);
    }
    const subdomainMap: Record<string, string> = {};
    if (subdomain) subdomainMap[subdomain] = pageId;
    for (const p of (allPublishedPages || []) as Array<{ id: string; subdomain: string }>) {
      const s = String(p.subdomain || '').trim().toLowerCase();
      if (s && !subdomainMap[s]) subdomainMap[s] = String(p.id);
    }
    await uploadOne(
      '_map.json',
      JSON.stringify({ generated_at: new Date().toISOString(), map: subdomainMap }, null, 2) + '\n',
      'application/json; charset=utf-8'
    );

    // ─── Canonical external URL the user shares / opens. We already know it
    // (knownBaseUrl) because Storage serving is deterministic — no two-pass
    // "deploy, learn the URL, re-deploy" dance needed anymore.
    const publishedBaseUrl = knownBaseUrl;
    const publishedUrl = `${publishedBaseUrl}/`;

    // ─── Update the row
    const publishedAt = new Date().toISOString();
    const { error: updateError } = await supabase
      .from('landing_pages')
      .update({
        status: 'published',
        published_at: publishedAt,
        published_url: publishedUrl
      } as any)
      .eq('id', pageId as any);
    if (updateError) {
      // Upload succeeded but the DB update failed — still return the URL so
      // the user can open the live page; the row just won't show "published".
      console.warn('Failed to update landing_pages row:', updateError.message);
    }

    return new Response(
      JSON.stringify({
        published_url: publishedUrl,
        published_base_url: publishedBaseUrl,
        published_at: publishedAt,
        storage_bucket: BUCKET,
        // Surface what the templates substituted so a debug dry-run can
        // inspect the value without scraping the rendered HTML.
        resolved: {
          subdomain,
          custom_domain: customDomain,
        }
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (err) {
    console.error('Publish error:', err);
    return new Response(
      JSON.stringify({ error: (err as Error)?.message || 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
