-- Migration placeholder for legacy cron config.
--
-- Previous versions relied on custom GUCs (app.settings.*) for pg_cron/pg_net calls.
-- Supabase does not support setting those reliably across environments, so this project
-- now stores runtime values in `public.app_runtime_settings` (see 20260209003000_*).
--
-- Intentionally a no-op.
